#!/usr/bin/env python3
"""Generate src/unicode_tables.h: codepoint ranges for the three classes the
GPT-2 pre-tokenizer regex uses, \\p{L} (letters), \\p{N} (numbers) and \\s
(whitespace), from Python's unicodedata, so the C++ tokenizer can classify
non-ASCII text the way HuggingFace's regex does. Offline tooling; the header
is committed. Run once per Python/Unicode version bump.
"""

import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src" / "unicode_tables.h"


def ranges(pred):
    out, start = [], None
    for cp in range(0x110000):
        ok = pred(cp)
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1)); start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def main():
    letters = ranges(lambda c: unicodedata.category(chr(c)).startswith("L"))
    numbers = ranges(lambda c: unicodedata.category(chr(c)).startswith("N"))
    spaces = ranges(lambda c: chr(c).isspace())
    lines = ["// unicode_tables.h — GENERATED by tools/gen_unicode_tables.py (Python",
             f"// {sys.version.split()[0]}, Unicode {unicodedata.unidata_version}). Do not edit.",
             "//", "// Inclusive codepoint ranges for the GPT-2 pre-tokenizer's character",
             "// classes: \\p{L} (all letter categories), \\p{N} (all number categories)",
             "// and \\s (Unicode whitespace). Sorted; look up with a binary search.",
             "#pragma once", "#include <cstdint>", "namespace llm::unicode {",
             "struct Range { uint32_t lo, hi; };"]
    for name, rs in (("kLetters", letters), ("kNumbers", numbers), ("kSpaces", spaces)):
        lines.append(f"inline constexpr Range {name}[] = {{")
        row = []
        for lo, hi in rs:
            row.append(f"{{0x{lo:X},0x{hi:X}}}")
            if len(row) == 6:
                lines.append("    " + ",".join(row) + ","); row = []
        if row:
            lines.append("    " + ",".join(row) + ",")
        lines.append("};")
        lines.append(f"inline constexpr int {name}Count = {len(rs)};")
    # NFC: canonical decompositions (recursive, full), combining classes, and
    # the primary composition pairs (canonical, not excluded).
    decomp, ccc, comp = [], [], []
    for cp in range(0x110000):
        ch = chr(cp)
        d = unicodedata.decomposition(ch)
        if d and not d.startswith("<"):
            full = unicodedata.normalize("NFD", ch)
            decomp.append((cp, [ord(c) for c in full]))
        c = unicodedata.combining(ch)
        if c:
            ccc.append((cp, c))
    for cp, seq in decomp:
        if len(seq) == 2 and unicodedata.normalize("NFC", "".join(map(chr, seq))) == chr(cp):
            comp.append((seq[0], seq[1], cp))
    comp.sort()
    lines.append("// NFC support: full canonical decompositions (cp -> up to 4 cps), canonical")
    lines.append("// combining classes, and primary composition pairs ((first, second) -> composed).")
    lines.append("struct Decomp { uint32_t cp; uint8_t n; uint32_t seq[4]; };")
    lines.append("struct Ccc { uint32_t cp; uint8_t ccc; };")
    lines.append("struct Comp { uint32_t a, b, c; };")
    lines.append("inline constexpr Decomp kDecomp[] = {")
    for cp, seq in decomp:
        seq = (seq + [0, 0, 0, 0])[:4]
        lines.append(f"    {{0x{cp:X},{len([x for x in seq if x])},{{{','.join(f'0x{x:X}' for x in seq)}}}}},")
    lines.append("};"); lines.append(f"inline constexpr int kDecompCount = {len(decomp)};")
    lines.append("inline constexpr Ccc kCcc[] = {")
    lines.append("    " + ",".join(f"{{0x{cp:X},{c}}}" for cp, c in ccc) + ",")
    lines.append("};"); lines.append(f"inline constexpr int kCccCount = {len(ccc)};")
    lines.append("inline constexpr Comp kComp[] = {")
    lines.append("    " + ",".join(f"{{0x{a:X},0x{b:X},0x{c:X}}}" for a, b, c in comp) + ",")
    lines.append("};"); lines.append(f"inline constexpr int kCompCount = {len(comp)};")
    lines.append("} // namespace llm::unicode")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}: {len(letters)} letter ranges, {len(numbers)} number ranges, {len(spaces)} space ranges, "
          f"{len(decomp)} decompositions, {len(ccc)} combining classes, {len(comp)} compositions")


if __name__ == "__main__":
    main()
